### ISSUE TITLE
Update README and tutorial to reference metadata analysis

### ISSUE THREAD

**Issue by aweinert-MIT** [LADI-Dataset/ladi-tutorial#16]
A [metadata analysis based on hurricane related flooding](https://github.com/LADI-Dataset/ladi-tutorial/blob/dev-metadata/Tutorials/Flood-Analysis.ipynb) was added in Merge Flood-Analysis notebook (#13) but there are no instructions or directions for the users on how or when to use them. Update the root README with the appropriate instructions.

**Comment by rearley516** [comment]
Flood Analysis.ipynb renamed Geospatial-Hurricane-Analysis.ipynb and updated README to reference new tutorial

**Comment by aweinert-MIT** [comment]
@rearley516 have you committed the code that addresses #15 , #16, #17? The dev-metadata branch hasn't been updated recently
