### ISSUE TITLE
Remove /Data and update Tutorials

### ISSUE THREAD

**Issue by aweinert-MIT** [LADI-Dataset/ladi-tutorial#17]
The [/Data directory](https://github.com/LADI-Dataset/ladi-tutorial/tree/dev-metadata/Data) was deprecated by [/data/metadata](https://github.com/LADI-Dataset/ladi-tutorial/tree/dev-metadata/data/metadata) by Merge Flood-Analysis notebook (#13). Remove [/Data directory](https://github.com/LADI-Dataset/ladi-tutorial/tree/dev-metadata/Data)  and update any of the markdown or scripts in [/Tutorials](https://github.com/LADI-Dataset/ladi-tutorial/tree/dev-metadata/Tutorials)

**Comment by rearley516** [comment]
Data directory removed and setup script updated to reference the set path
